### ISSUE TITLE
Deleting RF PolyLoads doesn't work again

### ISSUE THREAD

**Issue by LHesse2** [diego-apellaniz/Parametric-FEM-Toolbox#4]
Hello there again,
I'm working with the latest release but it seems that deleting PolyLoads doesn't work.
I tested deleting these in the previous patch and it worked fine, but now it doesn't.
Is there something special to consider and does it work for you?
Thank you very much!

**Comment by diego-apellaniz** [comment]
Hello there,
Deleteing PolyLoads is actually working for me. Can you send me the problematic file or/and a capture of the error please?

**Comment by LHesse2** [comment]
Hello,
While trying I sometimes get the components to work perfectly fine.
If I isolate the PolyLoad-deleting-workflow I can make it work.
The attached files contains my RFEM file with PolyLoads and a gh file with the working and the not working workflow.
I don't understand why adding more components to delete is causing this issue.

Thank you very much for your efforts!

[TestData_Polyload.zip](https://github.com/diego-apellaniz/Parametric-FEM-Toolbox/files/7082498/TestData_Polyload.zip)

**Comment by diego-apellaniz** [comment]
Hello,
sorry for my late response. Adding more components doesn't necessarly trigger an error BUT you have to check that you are not connecting null elements to the set data component. I think that's the issue here. If you get a null element from the get data component (or from somewhere else) because you select to import surfaces, but there are not surfaces and then you connect this null element with set data, this will cause an error.
